name: Merge Preprod PR (Every 5 minutes)
  # on:
  #   schedule:
  #     - cron:  '*/5 * * * *'
on:
  push:
    branches:
      - preprod

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: preprod

      - name: merge-pr
        run: |
          sleep 10
          gh pr merge preprod \
            --auto \
            --squash \
            --repo github.com/danieldides/test-repo-pls-ignore || echo "Nothing to merge"

      - name: reset preprod
        run: |
          sleep 5
          git fetch --no-tags --depth=1 origin/master master
          git fetch --no-tags --depth=1 origin/master preprod

          git reset --hard origin/master
          git push -f

