name: Merge Preprod PR (Every 5 minutes)
on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: preprod

      - name: merge-pr
        run: |
          gh pr merge preprod \
            --auto \
            --squash \
            --repo github.com/danieldides/test-repo-pls-ignore || echo "Nothing to merge"

      - name: reset preprod
        run: |
          # Bring preprod back up to speed with `release`
          git status
          git reset --hard origin/master
          git push -f

