name: Merge Preprod PR (Every 5 minutes)
  # on:
  #   schedule:
  #     - cron:  '*/5 * * * *'
on:
  push:
    branches:
      - preprod

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Get preprod branch
        run: |
          git fetch --no-tags --depth=1 origin master
          git fetch --no-tags --depth=1 origin preprod

      - name: merge-pr
        run: |
          sleep 40
          gh pr merge preprod \
            --auto \
            --squash \
            --repo github.com/danieldides/test-repo-pls-ignore || echo "Nothing to merge"

      - name: reset preprod
        run: |
          # Bring preprod back up to speed with `release`
          git status
          git reset --hard origin/master
          git push -f

