name: Stage Preprod PR
on:
  push:
    branches:
      - preprod

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      CURRENT_BRANCH: ${{github.base_ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set-env
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV


      - name: create-pr
        run: |
          gh pr create \
            --head preprod \
            --base master \
            --title "$(date -u '+%Y-%m-%d %H:%M:%S') - Release Preprod" \
            --body "This PR was created automatically. If all checks pass, this PR will be merged in 2 hours." \
            --repo github.com/danieldides/test-repo-pls-ignore || echo "PR already exists"

          echo github.base_ref
          echo $CURRENT_BRANCH

          echo "env"
          ${{ env.GITHUB_BRANCH }}

          echo "previous step"
          echo "GIT_BRANCH=${GIT_BRANCH}"

